# Generated by Django 4.1.13 on 2023-12-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('domain', models.CharField(max_length=50)),
                ('origin_server', models.CharField(max_length=100)),
                ('ssl_tls_config', models.CharField(max_length=50)),
                ('caching_policy', models.CharField(max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CDN',
        ),
    ]
