# Generated by Django 4.1.13 on 2023-12-11 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_distribution_delete_cdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='domain',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_domain', message='Enter a valid domain.', regex='^[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
    ]
